### PR TITLE
Change set_position method from POST to PUT, also send a random altit…

### PR DESCRIPTION
**Pull request by springjools**
…ude with the set_position call. This is for now just 20 meters +/- randowm within 10 meters. I also noticed that there is a 'hacc' and 'vacc' field in the response, but the put method seems to work without them. I believe that if you omit altitude or set it to 0, there will be no results returned by happn, or someehing like this.

Also cleaned up some empty spaces and put the content-length as strings as they are now required to be.

### CODE REVIEW

**Comment by mfld-fr** [comment]
Thank you Jools ! Mmm... does this PR also solve any opened issue ?

**Comment by springjools** [comment]
Yes, it solves #18 and also the set_position one, although there might be some further changes in the api

**Comment by rickhousley** [comment]
@springjools and @mfld-fr - thanks for the upkeep! Enjoy the holiday season.

**Comment by mfld-fr** [comment]
@rickhousley : you are welcome, have a nice end of year too !

**Pull request merged**
